name: Build and Deploy
env:
  CI: false
  USE_GITHUB_DATA: "false"
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1" # see https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3 # If you're using actions/checkout@v3 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20.x

      - name: Install and Build 🔧 # Build the Project
        run: |
          npm install
          npm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
